/**
 * @file CompactPhonemeDictionary.h
 * @brief Minimum-memory binary word->phoneme dictionary for TinyTTSTools
 * @author Phil Schatzmann
 * @version 1.0.0
 * @date 2025-09-07
 *
 * @copyright Copyright (c) 2025 Phil Schatzmann
 */

#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include "../Basic/Phonemes.h"
#include "PhonemeDictionaryBase.h"

/**
 * @brief Binary-search word->phoneme dictionary backed by four flat,
 * flash-resident arrays.
 * @details Replaces the old `PhonemeEntry{const char* word, const char*
 * phonemes}` table (two pointers per entry, plus a separately-stored,
 * null-terminated ASCII string for every word AND every phoneme sequence)
 * with:
 *  - `wordOffsets[count+1]`: cumulative offsets into `wordsBlob`
 *  - `wordsBlob`: every word's bytes concatenated, no separators/terminators
 *    (word i's length is `wordOffsets[i+1]-wordOffsets[i]`)
 *  - `phonemeOffsets[count+1]`: cumulative offsets into `phonemeData`
 *  - `phonemeData`: one byte per phoneme, packed as
 *    `(phoneme_id << 2) | stress`, where phoneme_id indexes
 *    Phonemes::getPhonemeById() (see the `Phone` enum in Phonemes.h) and
 *    stress is 0 (none), 1 (primary) or 2 (secondary) -- decoded back into
 *    a space-separated ARPABET string, e.g. "HH AH0 L OW1".
 *
 * This drops both the two-pointers-per-entry overhead and the ASCII-text
 * cost of storing phonemes as multi-character tokens with spaces and a
 * null terminator (1 byte per phoneme here vs. 3-4+ ASCII bytes). All four
 * arrays are position-independent (offsets only, never pointers into each
 * other), so they can be built by hand, generated by a script (see
 * setup/dictionary for the full CMU-dictionary port), or -- for
 * hand-maintained tables -- produced at COMPILE TIME from a readable
 * `{"word", "PHONEMES"}` source table via CompactPhonemeDictionaryBuilder.h,
 * so no separate build step is needed to keep them in sync.
 *
 * Entries must be sorted by word (binary search), exactly like the old
 * PhonemeEntry tables.
 */
class CompactPhonemeDictionary : public PhonemeDictionaryBase {
 public:
  CompactPhonemeDictionary() = default;

  CompactPhonemeDictionary(const uint32_t* wordOffsets, const char* wordsBlob,
                           const uint32_t* phonemeOffsets, const uint8_t* phonemeData,
                           size_t count) {
    begin(wordOffsets, wordsBlob, phonemeOffsets, phonemeData, count);
  }

  /// (Re)point this dictionary at the four backing arrays. None of the
  /// pointers are copied -- they must outlive this object.
  bool begin(const uint32_t* wordOffsets, const char* wordsBlob,
            const uint32_t* phonemeOffsets, const uint8_t* phonemeData,
            size_t count) {
    wordOffsets_ = wordOffsets;
    wordsBlob_ = wordsBlob;
    phonemeOffsets_ = phonemeOffsets;
    phonemeData_ = phonemeData;
    count_ = count;
    return count_ > 0;
  }

  /// Number of words in the dictionary.
  size_t size() const override { return count_; }

  /// Binary-search for `word` (must already be lowercase, matching how the
  /// dictionary was built). On success, fills `outPhonemes` with a
  /// space-separated ARPABET phoneme string and returns true.
  bool lookup(const std::string& word, std::string& outPhonemes) const override {
    if (wordOffsets_ == nullptr || count_ == 0) return false;
    int32_t lo = 0, hi = static_cast<int32_t>(count_) - 1;
    while (lo <= hi) {
      int32_t mid = lo + (hi - lo) / 2;
      int cmp = compareWord(static_cast<uint32_t>(mid), word);
      if (cmp == 0) {
        decodePhonemes(static_cast<uint32_t>(mid), outPhonemes);
        return true;
      } else if (cmp < 0) {
        lo = mid + 1;
      } else {
        hi = mid - 1;
      }
    }
    return false;
  }

  using PhonemeDictionaryBase::lookup;  // bring in the single-arg convenience overload

  /// Word at sequential index `idx` (0..size()-1), for iterating the whole
  /// dictionary (e.g. evaluation/tooling) rather than looking one up by name.
  std::string wordAt(size_t idx) const {
    uint32_t start = wordOffsets_[idx];
    uint32_t end = wordOffsets_[idx + 1];
    return std::string(wordsBlob_ + start, end - start);
  }

  /// Space-separated ARPABET phoneme string at sequential index `idx`.
  std::string phonemesAt(size_t idx) const {
    std::string out;
    decodePhonemes(static_cast<uint32_t>(idx), out);
    return out;
  }

 protected:
  const uint32_t* wordOffsets_ = nullptr;
  const char* wordsBlob_ = nullptr;
  const uint32_t* phonemeOffsets_ = nullptr;
  const uint8_t* phonemeData_ = nullptr;
  size_t count_ = 0;

  int compareWord(uint32_t idx, const std::string& word) const {
    uint32_t start = wordOffsets_[idx];
    uint32_t end = wordOffsets_[idx + 1];
    size_t wlen = end - start;
    const char* w = wordsBlob_ + start;
    size_t minLen = wlen < word.size() ? wlen : word.size();
    int cmp = std::memcmp(w, word.data(), minLen);
    if (cmp != 0) return cmp;
    return static_cast<int>(wlen) - static_cast<int>(word.size());
  }

  void decodePhonemes(uint32_t idx, std::string& out) const {
    out.clear();
    uint32_t start = phonemeOffsets_[idx];
    uint32_t end = phonemeOffsets_[idx + 1];
    const uint8_t* p = phonemeData_ + start;
    // One shared, lazily-constructed lookup table for id -> ARPABET string
    // (function-local static: built once, not once per lookup/instance).
    static const Phonemes phonemeTable;
    for (uint32_t i = 0; i < end - start; ++i) {
      uint8_t b = p[i];
      uint8_t id = b >> 2;
      uint8_t stress = b & 0x3;
      const PhonemeInfo* info = phonemeTable.getPhonemeById(id);
      if (!info) continue;
      if (!out.empty()) out += ' ';
      out += info->arpabet;
      if (stress != 0) out += static_cast<char>('0' + stress);
    }
  }
};
