#!/usr/bin/env python3
"""
Generate ArpabetAltWAVDictionary.h (and its Data/wav/arpabet_alt.h umbrella
header) from the existing {PHONEME}_SIL diphone data.

ArpabetAltWAVDictionary is an alternative single-phoneme dictionary built by
reusing each phoneme's own "phoneme -> SIL" diphone (i.e. the second half of
the phoneme trailing off into silence) as a standalone phoneme sound. That
diphone data is real IMA-ADPCM (WAVE_FORMAT_IMA_ADPCM, 4 bits/sample,
256-byte blocks -- see generate_wav_dictionary.py / AudioFormatDecoder.h),
NOT PCM8, so the SoundEntry values here must use bits=4 like DIPHONES does.

This script does not regenerate the underlying diphones/{P}_SIL.h data files
(generate_relevant_diphones.sh + generate_wav_dictionary.py own that); it
only assembles the ArpabetAlt-specific dictionary header from data that
already exists in src/TinyTTSTools/Data/wav/diphones/.
"""

from pathlib import Path

# The 39 base ARPAbet phonemes (no stress digits) this alternate dictionary
# covers -- matches the phoneme set generate_relevant_diphones.sh produces
# {P}_SIL diphones for.
PHONEMES = [
    "AA", "AE", "AH", "AO", "AW", "AY", "B", "CH", "D", "DH",
    "EH", "ER", "EY", "F", "G", "HH", "IH", "IY", "JH", "K",
    "L", "M", "N", "NG", "OW", "OY", "P", "R", "S", "SH",
    "T", "TH", "UH", "UW", "V", "W", "Y", "Z", "ZH",
]


def main():
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent.parent.parent
    diphones_dir = repo_root / "src/TinyTTSTools/Data/wav/diphones"
    data_wav_dir = repo_root / "src/TinyTTSTools/Data/wav"
    dict_dir = repo_root / "src/TinyTTSTools/Dictionary"

    missing = [p for p in PHONEMES if not (diphones_dir / f"{p}_SIL.h").exists()]
    if missing:
        raise SystemExit(f"Missing diphone header(s) for: {missing} in {diphones_dir}")

    # Umbrella header: Data/wav/arpabet_alt.h including each diphones/{P}_SIL.h
    umbrella_lines = ["#pragma once", ""]
    for p in PHONEMES:
        umbrella_lines.append(f'#include "diphones/{p}_SIL.h"')
    umbrella_file = data_wav_dir / "arpabet_alt.h"
    umbrella_file.write_text("\n".join(umbrella_lines) + "\n")
    print(f"Wrote {umbrella_file}")

    # Main dictionary header
    lines = []
    lines.append("#pragma once")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("#include <vector>")
    lines.append("#include <cstring>")
    lines.append('#include "AudioDictionary.h"')
    lines.append('#include "SoundEntry.h"')
    lines.append('#include "../Data/wav/arpabet_alt.h"')
    lines.append("")
    lines.append("// Auto-generated single-phoneme dictionary reusing each phoneme's own")
    lines.append("// {PHONEME}_SIL diphone (phoneme trailing into silence) as a standalone")
    lines.append("// phoneme sound. Source data is real IMA-ADPCM (bits=4), not PCM8.")
    lines.append("// Generated by generate_arpabet_alt_dictionary.py")
    lines.append("//")
    lines.append("// WARNING: each entry's real audio content is only ~half of the")
    lines.append("// phoneme's natural duration (see Phonemes.h's phoneme_map) plus a")
    lines.append("// ~50ms silence handoff -- that's how generate_relevant_diphones.sh")
    lines.append("// builds a {P}_SIL diphone for concatenation, not a full standalone")
    lines.append("// phoneme. PhonemeVocoder requests each phoneme's FULL table")
    lines.append("// duration, so playing this dictionary back plays every phoneme (most")
    lines.append("// audibly, vowels) for only about half its intended length before it")
    lines.append("// trails into silence. Use ArpabetWAVDictionary (from")
    lines.append("// setup/audio/phonemes-from-espeak/) for real standalone phonemes;")
    lines.append("// this dictionary exists only to regression-test the ADPCM decoder")
    lines.append("// against known-good diphone data (see tests/test_audio_format_decoder.cpp).")
    lines.append("")
    lines.append("// Array of all ARPAbet phonemes")
    lines.append(f"const SoundEntry ARPABET_ALT_PHONEMES[{len(PHONEMES)}] = {{")
    for i, p in enumerate(PHONEMES):
        comma = "," if i < len(PHONEMES) - 1 else ""
        array_name = f"sound_data_{p}_SIL"
        lines.append(f'    SoundEntry("{p}", {array_name}_size, {array_name}, 4){comma}')
    lines.append("};")
    lines.append("")
    lines.append("// Total number of ARPAbet phonemes")
    lines.append(f"const size_t NUM_ARPABET_ALT_PHONEMES = {len(PHONEMES)};")
    lines.append("")
    lines.append("/**")
    lines.append(" * @brief Static global AudioDictionary instance with ARPAbet WAV phonemes")
    lines.append(" * @details This global variable provides immediate access to the ARPAbet")
    lines.append(f" *          phoneme dictionary without needing to instantiate a class. It's")
    lines.append(f" *          automatically initialized with all {len(PHONEMES)} ARPAbet phonemes at")
    lines.append(" *          8kHz sample rate, sourced from IMA-ADPCM diphone data.")
    lines.append(" */")
    lines.append(
        "static AudioDictionary ArpabetAltWAVDictionary(ARPABET_ALT_PHONEMES, "
        "NUM_ARPABET_ALT_PHONEMES, 8000, PhonemeType::ARPAbet, 1, 16);"
    )

    out_file = dict_dir / "ArpabetAltWAVDictionary.h"
    out_file.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_file}")


if __name__ == "__main__":
    main()
