#!/usr/bin/env python3
"""
Generate a C++ header file with SoundEntry array from ADPCM WAV files.
This script reads all WAV files from the diphones/adpcm directory and
generates a header file containing the binary data as C++ arrays.
"""

import os
import struct
from pathlib import Path

def read_wav_data(file_path):
    """Read WAV file and extract the audio data portion (skip header)"""
    with open(file_path, 'rb') as f:
        # Read WAV header to find data chunk
        # Standard WAV format: RIFF header (12 bytes) + fmt chunk + data chunk
        f.read(4)  # "RIFF"
        file_size = struct.unpack('<I', f.read(4))[0]
        f.read(4)  # "WAVE"
        
        # Find data chunk
        while True:
            chunk_id = f.read(4)
            if len(chunk_id) < 4:
                break
            chunk_size = struct.unpack('<I', f.read(4))[0]
            
            if chunk_id == b'data':
                # Found data chunk, read the audio data
                return f.read(chunk_size)
            else:
                # Skip this chunk
                f.read(chunk_size)
                # Handle odd-sized chunks (WAV format requires even alignment)
                if chunk_size % 2 == 1:
                    f.read(1)
        
        return b''  # No data chunk found

def generate_cpp_headers(input_dir, output_dir):
    """Generate separate C++ header files for each WAV file and a main dictionary header"""
    
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    
    if not input_path.exists():
        print(f"Error: Directory {input_dir} does not exist!")
        return
    
    # Create output directory if it doesn't exist
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Get all WAV files
    wav_files = sorted(input_path.glob("*.wav"))
    
    if not wav_files:
        print(f"No WAV files found in {input_dir}")
        return
    
    print(f"Found {len(wav_files)} WAV files to process...")
    
    # Generate individual header files for each WAV file
    sound_entries = []
    
    for wav_file in wav_files:
        # Get filename without extension
        name = wav_file.stem
        
        # Read WAV data
        try:
            wav_data = read_wav_data(wav_file)
            if not wav_data:
                print(f"Warning: No data found in {wav_file}")
                continue
                
            # Generate C++ array name (replace special chars with underscores)
            array_name = f"sound_data_{name.replace('-', '_').replace(' ', '_')}"
            
            # Generate individual header file content
            individual_header_content = []
            individual_header_content.append('#pragma once')
            individual_header_content.append('#include <cstdint>')
            individual_header_content.append('')
            individual_header_content.append(f'// Auto-generated sound data for {name}')
            individual_header_content.append('// Generated by generate_wav_dictionary.py')
            individual_header_content.append('')
            individual_header_content.append(f'// Data for {name}')
            individual_header_content.append(f'const uint8_t {array_name}[] = {{')
            
            # Convert bytes to hex values, 16 per line
            hex_values = []
            for i, byte in enumerate(wav_data):
                hex_values.append(f'0x{byte:02X}')
                if (i + 1) % 16 == 0:
                    individual_header_content.append(f'    {", ".join(hex_values)},')
                    hex_values = []
            
            # Add remaining bytes
            if hex_values:
                individual_header_content.append(f'    {", ".join(hex_values)}')
            
            individual_header_content.append('};')
            individual_header_content.append('')
            individual_header_content.append(f'// Size of the data array')
            individual_header_content.append(f'const size_t {array_name}_size = {len(wav_data)};')
            
            # Write individual header file
            individual_header_file = output_path / f"{name}.h"
            with open(individual_header_file, 'w') as f:
                f.write('\n'.join(individual_header_content))
            
            # Store entry info
            sound_entries.append({
                'name': name,
                'array_name': array_name,
                'size': len(wav_data),
                'header_file': f"{name}.h"
            })
            
            print(f"Generated {individual_header_file}: {len(wav_data)} bytes")
            
        except Exception as e:
            print(f"Error processing {wav_file}: {e}")
            continue
    
    # Generate an umbrella header that just #includes every individual
    # per-diphone header, one level up from output_path (Data/wav/), e.g.
    # Data/wav/diphones.h including Data/wav/diphones/AA_B.h -- matches the
    # convention already used for the ARPAbet phoneme data
    # (Data/wav/arpabet.h), so the main dictionary header below doesn't
    # need 877 individual #include lines of its own.
    umbrella_content = ['#pragma once', '']
    for entry in sound_entries:
        umbrella_content.append(f'#include "diphones/{entry["header_file"]}"')
    umbrella_file = output_path.parent / "diphones.h"
    with open(umbrella_file, 'w') as f:
        f.write('\n'.join(umbrella_content) + '\n')
    print(f"Wrote umbrella header: {umbrella_file}")

    # Generate the main dictionary header file
    main_header_content = []
    main_header_content.append('#pragma once')
    main_header_content.append('#include "SoundEntry.h"')
    main_header_content.append('#include <cstdint>')
    main_header_content.append('#include <cstddef>')
    main_header_content.append('')
    main_header_content.append('#include "../Data/wav/diphones.h"')
    main_header_content.append('')
    main_header_content.append('// Auto-generated sound dictionary from ADPCM WAV files')
    main_header_content.append('// Generated by generate_wav_dictionary.py')
    main_header_content.append('')

    # Generate the SoundEntry array (symbolic _size references, not literal
    # byte counts, so the array can never silently drift out of sync with
    # the data it points at)
    main_header_content.append('// Array of all diphones')
    main_header_content.append(f'const SoundEntry DIPHONES[{len(sound_entries)}] = {{')

    for i, entry in enumerate(sound_entries):
        comma = ',' if i < len(sound_entries) - 1 else ''
        # bits=4: this data is IMA-ADPCM (see AudioFormatDecoder.h), not
        # PCM16 -- omitting it used to silently default to 16 (raw PCM16),
        # which reinterpreted the compressed ADPCM bytes as noise.
        main_header_content.append(
            f'    SoundEntry("{entry["name"]}", {entry["array_name"]}_size, {entry["array_name"]}, 4){comma}')

    main_header_content.append('};')
    main_header_content.append('')
    main_header_content.append(f'// Total number of diphones')
    main_header_content.append(f'const size_t NUM_DIPHONES = {len(sound_entries)};')

    # Write main dictionary header file directly to
    # src/TinyTTSTools/Dictionary/DiphoneWAVDictionary.h (a sibling of
    # Data/, not output_path.parent.parent -- that stale assumption
    # predates the Data/ subfolder reorg and pointed at
    # src/TinyTTSTools/DiphoneWAVDictionary.h, which nothing includes).
    main_header_file = output_path.parent.parent.parent / "Dictionary" / "DiphoneWAVDictionary.h"
    try:
        with open(main_header_file, 'w') as f:
            f.write('\n'.join(main_header_content))
        print(f"\nSuccessfully generated {main_header_file}")
        print(f"Total diphones: {len(sound_entries)}")

        # Calculate total size
        total_size = sum(entry['size'] for entry in sound_entries)
        print(f"Total data size: {total_size} bytes ({total_size/1024:.1f} KB)")

    except Exception as e:
        print(f"Error writing to {main_header_file}: {e}")

def main():
    # Configuration
    input_directory = "adpcm"
    output_directory = "../../../src/TinyTTSTools/Data/wav/diphones"

    print("ADPCM WAV to C++ Header Generator")
    print("=" * 40)

    # Generate the header files
    generate_cpp_headers(input_directory, output_directory)

if __name__ == "__main__":
    main()
