var searchData=
[
  ['finalizesamplenasallp_0',['finalizeSampleNasalLP',['../classFormantVocoder.html#affdbb720553a94978a035cecb61f0843',1,'FormantVocoder']]],
  ['findoptimalendpoint_1',['findOptimalEndPoint',['../classConcatenatedAudioVocoder.html#a0c8bcf9c536a9ebeea2e9aebcf52ac94',1,'ConcatenatedAudioVocoder']]],
  ['findoptimalstartpoint_2',['findOptimalStartPoint',['../classConcatenatedAudioVocoder.html#ad445da669f0fbb3281eff7a9b97af934',1,'ConcatenatedAudioVocoder']]],
  ['findphonemerule_3',['findPhonemeRule',['../classFormantVocoder.html#a94d44e6314cd8666a27353c701a01a6e',1,'FormantVocoder']]],
  ['flushbatch_4',['flushBatch',['../classConcatenatedAudioVocoder.html#a0c285cfcfed390fc1bc72bb84632e88c',1,'ConcatenatedAudioVocoder']]],
  ['formantvocoder_5',['FormantVocoder',['../classFormantVocoder.html#a5819713969ac11ef50c465690233a893',1,'FormantVocoder']]],
  ['formantvoiceconfig_6',['FormantVoiceConfig',['../structFormantVoiceConfig.html#ad0ab35d9066b5f97c1d933ed95028c34',1,'FormantVoiceConfig::FormantVoiceConfig()=default'],['../structFormantVoiceConfig.html#ab4314fe8e1e4ea8a6f629687b6b531a8',1,'FormantVoiceConfig::FormantVoiceConfig(float baseF0, float jitterPct, float shimmerPct, float breathiness, float spectralTilt, float pitchFallPerSec, bool enableF4, float overlapMs, float sibilantGain, float postalveolarGain, float fricativeMaxPeak, float targetRMS, float fricativeTargetRMS, float rmsAdaptRate, float deEsserThreshold, float deEsserAtten, float nasalLowpass, bool enableFormantRandom, float formantRandomCents, float bandwidthRandomPct, bool enableStressPitch, float stressPitchRisePrimary, float stressPitchRiseSecondary, float stressEnergyBoostPrimary, float stressEnergyBoostSecondary, float stressDecayPortion, bool enableNasalNotch, float nasalNotchFreq1, float nasalNotchBw1, float nasalNotchFreq2, float nasalNotchBw2, float nasalNotchDepth, float sibilantHFFormantScale, float sibilantDynamicTargetRMS, float sibilantCompressionRatio, float sibilantAttack, float sibilantRelease, float sibilantFinalGain, float sibilantLowpassMix)']]]
];
