#pragma once
#include <cstddef>
#include <cstdint>
#include <vector>
#include <cstring>
#include "AudioDictionary.h"
#include "SoundEntry.h"
#include "../Data/wav/arpabet.h"

// Auto-generated phoneme dictionary from PCM8 WAV files
// Generated by generate_wav_dictionary.py

// Array of all ARPAbet phonemes
const SoundEntry ARPABET_PHONEMES[65] = {
    SoundEntry("AA", 1190, phoneme_data_AA, 8),
    SoundEntry("AE", 980, phoneme_data_AE, 8),
    SoundEntry("AF:", 1741, phoneme_data_AF_, 8),
    SoundEntry("AF", 1050, phoneme_data_AF, 8),
    SoundEntry("AH", 910, phoneme_data_AH, 8),
    SoundEntry("AH0", 630, phoneme_data_AH0, 8),
    SoundEntry("AN", 1350, phoneme_data_AN, 8),
    SoundEntry("AO", 1260, phoneme_data_AO, 8),
    SoundEntry("AW", 1400, phoneme_data_AW, 8),
    SoundEntry("AY", 1400, phoneme_data_AY, 8),
    SoundEntry("B", 560, phoneme_data_B, 8),
    SoundEntry("BETA", 750, phoneme_data_BETA, 8),
    SoundEntry("C", 798, phoneme_data_C, 8),
    SoundEntry("CH", 910, phoneme_data_CH, 8),
    SoundEntry("D", 420, phoneme_data_D, 8),
    SoundEntry("DH", 770, phoneme_data_DH, 8),
    SoundEntry("EH", 980, phoneme_data_EH, 8),
    SoundEntry("EN", 1350, phoneme_data_EN, 8),
    SoundEntry("EP", 975, phoneme_data_EP, 8),
    SoundEntry("ER", 1120, phoneme_data_ER, 8),
    SoundEntry("ER0", 700, phoneme_data_ER0, 8),
    SoundEntry("EY", 1330, phoneme_data_EY, 8),
    SoundEntry("F", 910, phoneme_data_F, 8),
    SoundEntry("G", 560, phoneme_data_G, 8),
    SoundEntry("GH", 750, phoneme_data_GH, 8),
    SoundEntry("HH", 700, phoneme_data_HH, 8),
    SoundEntry("HU", 610, phoneme_data_HU, 8),
    SoundEntry("IH", 840, phoneme_data_IH, 8),
    SoundEntry("IY", 1120, phoneme_data_IY, 8),
    SoundEntry("JH", 840, phoneme_data_JH, 8),
    SoundEntry("K", 630, phoneme_data_K, 8),
    SoundEntry("L", 770, phoneme_data_L, 8),
    SoundEntry("LY", 825, phoneme_data_LY, 8),
    SoundEntry("M", 770, phoneme_data_M, 8),
    SoundEntry("N", 700, phoneme_data_N, 8),
    SoundEntry("NG", 840, phoneme_data_NG, 8),
    SoundEntry("NY", 900, phoneme_data_NY, 8),
    SoundEntry("OE", 1088, phoneme_data_OE, 8),
    SoundEntry("OF", 1161, phoneme_data_OF, 8),
    SoundEntry("ON", 1350, phoneme_data_ON, 8),
    SoundEntry("OP", 975, phoneme_data_OP, 8),
    SoundEntry("OW", 1330, phoneme_data_OW, 8),
    SoundEntry("OY", 1400, phoneme_data_OY, 8),
    SoundEntry("P", 630, phoneme_data_P, 8),
    SoundEntry("PF", 653, phoneme_data_PF, 8),
    SoundEntry("R", 700, phoneme_data_R, 8),
    SoundEntry("RR", 1200, phoneme_data_RR, 8),
    SoundEntry("RT", 300, phoneme_data_RT, 8),
    SoundEntry("RU", 798, phoneme_data_RU, 8),
    SoundEntry("S", 980, phoneme_data_S, 8),
    SoundEntry("SH", 910, phoneme_data_SH, 8),
    SoundEntry("T", 560, phoneme_data_T, 8),
    SoundEntry("TH", 840, phoneme_data_TH, 8),
    SoundEntry("TS", 653, phoneme_data_TS, 8),
    SoundEntry("UF", 1161, phoneme_data_UF, 8),
    SoundEntry("UF0", 871, phoneme_data_UF0, 8),
    SoundEntry("UH", 910, phoneme_data_UH, 8),
    SoundEntry("UN", 1350, phoneme_data_UN, 8),
    SoundEntry("UW", 1190, phoneme_data_UW, 8),
    SoundEntry("V", 770, phoneme_data_V, 8),
    SoundEntry("W", 630, phoneme_data_W, 8),
    SoundEntry("X", 871, phoneme_data_X, 8),
    SoundEntry("Y", 560, phoneme_data_Y, 8),
    SoundEntry("Z", 840, phoneme_data_Z, 8),
    SoundEntry("ZH", 840, phoneme_data_ZH, 8)
};

// Total number of ARPAbet phonemes
const size_t NUM_ARPABET_PHONEMES = 65;

/**
 * @brief Static global AudioDictionary instance with ARPAbet WAV phonemes
 * @details This global variable provides immediate access to the ARPAbet phoneme dictionary
 *          without needing to instantiate a class. It's automatically initialized with
 *          all 65 ARPAbet phonemes at 8kHz sample rate with 8-bit source data.
 */
static AudioDictionary ArpabetWAVDictionary(ARPABET_PHONEMES, NUM_ARPABET_PHONEMES, 8000, PhonemeType::ARPAbet, 1, 16);