#pragma once
#include <cstddef>
#include <cstdint>
#include <vector>
#include <cstring>
#include "AudioDictionary.h"
#include "SoundEntry.h"
#include "../Data/wav/arpabet_alt.h"

// Auto-generated single-phoneme dictionary reusing each phoneme's own
// {PHONEME}_SIL diphone (phoneme trailing into silence) as a standalone
// phoneme sound. Source data is real IMA-ADPCM (bits=4), not PCM8.
// Generated by generate_arpabet_alt_dictionary.py
//
// WARNING: each entry's real audio content is only ~half of the
// phoneme's natural duration (see Phonemes.h's phoneme_map) plus a
// ~50ms silence handoff -- that's how generate_relevant_diphones.sh
// builds a {P}_SIL diphone for concatenation, not a full standalone
// phoneme. PhonemeVocoder requests each phoneme's FULL table
// duration, so playing this dictionary back plays every phoneme (most
// audibly, vowels) for only about half its intended length before it
// trails into silence. Use ArpabetWAVDictionary (from
// setup/audio/phonemes-from-espeak/) for real standalone phonemes;
// this dictionary exists only to regression-test the ADPCM decoder
// against known-good diphone data (see tests/test_audio_format_decoder.cpp).

// Array of all ARPAbet phonemes
const SoundEntry ARPABET_ALT_PHONEMES[39] = {
    SoundEntry("AA", sound_data_AA_SIL_size, sound_data_AA_SIL, 4),
    SoundEntry("AE", sound_data_AE_SIL_size, sound_data_AE_SIL, 4),
    SoundEntry("AH", sound_data_AH_SIL_size, sound_data_AH_SIL, 4),
    SoundEntry("AO", sound_data_AO_SIL_size, sound_data_AO_SIL, 4),
    SoundEntry("AW", sound_data_AW_SIL_size, sound_data_AW_SIL, 4),
    SoundEntry("AY", sound_data_AY_SIL_size, sound_data_AY_SIL, 4),
    SoundEntry("B", sound_data_B_SIL_size, sound_data_B_SIL, 4),
    SoundEntry("CH", sound_data_CH_SIL_size, sound_data_CH_SIL, 4),
    SoundEntry("D", sound_data_D_SIL_size, sound_data_D_SIL, 4),
    SoundEntry("DH", sound_data_DH_SIL_size, sound_data_DH_SIL, 4),
    SoundEntry("EH", sound_data_EH_SIL_size, sound_data_EH_SIL, 4),
    SoundEntry("ER", sound_data_ER_SIL_size, sound_data_ER_SIL, 4),
    SoundEntry("EY", sound_data_EY_SIL_size, sound_data_EY_SIL, 4),
    SoundEntry("F", sound_data_F_SIL_size, sound_data_F_SIL, 4),
    SoundEntry("G", sound_data_G_SIL_size, sound_data_G_SIL, 4),
    SoundEntry("HH", sound_data_HH_SIL_size, sound_data_HH_SIL, 4),
    SoundEntry("IH", sound_data_IH_SIL_size, sound_data_IH_SIL, 4),
    SoundEntry("IY", sound_data_IY_SIL_size, sound_data_IY_SIL, 4),
    SoundEntry("JH", sound_data_JH_SIL_size, sound_data_JH_SIL, 4),
    SoundEntry("K", sound_data_K_SIL_size, sound_data_K_SIL, 4),
    SoundEntry("L", sound_data_L_SIL_size, sound_data_L_SIL, 4),
    SoundEntry("M", sound_data_M_SIL_size, sound_data_M_SIL, 4),
    SoundEntry("N", sound_data_N_SIL_size, sound_data_N_SIL, 4),
    SoundEntry("NG", sound_data_NG_SIL_size, sound_data_NG_SIL, 4),
    SoundEntry("OW", sound_data_OW_SIL_size, sound_data_OW_SIL, 4),
    SoundEntry("OY", sound_data_OY_SIL_size, sound_data_OY_SIL, 4),
    SoundEntry("P", sound_data_P_SIL_size, sound_data_P_SIL, 4),
    SoundEntry("R", sound_data_R_SIL_size, sound_data_R_SIL, 4),
    SoundEntry("S", sound_data_S_SIL_size, sound_data_S_SIL, 4),
    SoundEntry("SH", sound_data_SH_SIL_size, sound_data_SH_SIL, 4),
    SoundEntry("T", sound_data_T_SIL_size, sound_data_T_SIL, 4),
    SoundEntry("TH", sound_data_TH_SIL_size, sound_data_TH_SIL, 4),
    SoundEntry("UH", sound_data_UH_SIL_size, sound_data_UH_SIL, 4),
    SoundEntry("UW", sound_data_UW_SIL_size, sound_data_UW_SIL, 4),
    SoundEntry("V", sound_data_V_SIL_size, sound_data_V_SIL, 4),
    SoundEntry("W", sound_data_W_SIL_size, sound_data_W_SIL, 4),
    SoundEntry("Y", sound_data_Y_SIL_size, sound_data_Y_SIL, 4),
    SoundEntry("Z", sound_data_Z_SIL_size, sound_data_Z_SIL, 4),
    SoundEntry("ZH", sound_data_ZH_SIL_size, sound_data_ZH_SIL, 4)
};

// Total number of ARPAbet phonemes
const size_t NUM_ARPABET_ALT_PHONEMES = 39;

/**
 * @brief Static global AudioDictionary instance with ARPAbet WAV phonemes
 * @details This global variable provides immediate access to the ARPAbet
 *          phoneme dictionary without needing to instantiate a class. It's
 *          automatically initialized with all 39 ARPAbet phonemes at
 *          8kHz sample rate, sourced from IMA-ADPCM diphone data.
 */
static AudioDictionary ArpabetAltWAVDictionary(ARPABET_ALT_PHONEMES, NUM_ARPABET_ALT_PHONEMES, 8000, PhonemeType::ARPAbet, 1, 16);
