/**
 * @file CompactPhonemeDictionaryBuilder.h
 * @brief Compile-time builder that packs a readable, enum-typed
 * {"word", Phone::X, Phone::Y, ...} table into the flat arrays
 * CompactPhonemeDictionary reads.
 * @author Phil Schatzmann
 * @version 1.0.0
 * @date 2025-09-07
 *
 * @copyright Copyright (c) 2025 Phil Schatzmann
 */

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include "CompactPhonemeDictionary.h"

/// One human-readable dictionary source entry: a word and a pointer to its
/// already-packed phoneme sequence (see PH_WORD() below -- entries are
/// built with that macro, never written out by hand).
struct PhonemeWordSource {
  const char* word;
  const uint8_t* phonemeData;
  size_t phonemeCount;
};

namespace tts_compact_dict_detail {

constexpr size_t cxStrLen(const char* s) {
  size_t n = 0;
  while (s[n] != '\0') ++n;
  return n;
}

/// true if a is strictly less than b, comparing byte-by-byte (matches the
/// std::memcmp-based ordering CompactPhonemeDictionary's binary search uses).
constexpr bool cxWordLess(const char* a, const char* b) {
  size_t i = 0;
  while (a[i] != '\0' && b[i] != '\0') {
    if (a[i] != b[i]) return static_cast<unsigned char>(a[i]) < static_cast<unsigned char>(b[i]);
    ++i;
  }
  return a[i] == '\0' && b[i] != '\0';
}

/// phoneme_map/getPhonemeById() ids (see Phonemes.h) for the 15 vowels that
/// have `Phone::X1`/`Phone::X2` stressed-variant enum members, in the same
/// order those variants are declared (Phone::AA1 first, Phone::UW2 last) --
/// index i corresponds to enum values (43 + 2*i) and (43 + 2*i + 1).
constexpr uint8_t kStressedVowelBaseIds[15] = {2, 3, 4, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18};

/// Packs one `Phone` value into a single dictionary byte: (base_id << 2) |
/// stress. Plain `Phone` members (0-42) already are phoneme_map/
/// getPhonemeById() ids and always mean stress 0; the stressed-variant
/// members (43+, e.g. Phone::AH1) decode via kStressedVowelBaseIds.
constexpr uint8_t cxPackPhone(Phone p) {
  uint8_t v = static_cast<uint8_t>(p);
  if (v <= 42) return static_cast<uint8_t>(v << 2);
  uint8_t idx = static_cast<uint8_t>(v - 43);
  uint8_t baseId = kStressedVowelBaseIds[idx / 2];
  uint8_t stress = static_cast<uint8_t>((idx % 2) + 1);
  return static_cast<uint8_t>((baseId << 2) | stress);
}

template <size_t N>
constexpr size_t cxTotalWordBytes(const PhonemeWordSource (&table)[N]) {
  size_t total = 0;
  for (size_t i = 0; i < N; ++i) total += cxStrLen(table[i].word);
  return total;
}

template <size_t N>
constexpr size_t cxTotalPhonemeCount(const PhonemeWordSource (&table)[N]) {
  size_t total = 0;
  for (size_t i = 0; i < N; ++i) total += table[i].phonemeCount;
  return total;
}

/// Backing storage for one word's packed phoneme sequence -- one
/// instantiation per unique `<Ps...>` combination (so identical
/// pronunciations, e.g. true homophones, automatically share storage).
template <Phone... Ps>
struct PhonemeSeqHolder {
  static constexpr uint8_t values[sizeof...(Ps)] = {cxPackPhone(Ps)...};
};
template <Phone... Ps>
constexpr uint8_t PhonemeSeqHolder<Ps...>::values[sizeof...(Ps)];

template <Phone... Ps>
constexpr PhonemeWordSource makeWord(const char* word) {
  return PhonemeWordSource{word, PhonemeSeqHolder<Ps...>::values, sizeof...(Ps)};
}

}  // namespace tts_compact_dict_detail

/// Builds one dictionary table row: `PH_WORD("able", Phone::EY, Phone::B,
/// Phone::AH, Phone::L)`. Each argument after the word must be a `Phone`
/// enum value (see Phonemes.h) -- an unrecognized ARPABET name is simply a
/// compiler error (no name of that kind exists), so there's no separate
/// "unknown token" check to run at dictionary-build time.
#define PH_WORD(word, ...) tts_compact_dict_detail::makeWord<__VA_ARGS__>(word)

/**
 * @brief Compile-time-computed compact dictionary data for a readable,
 * PH_WORD()-built `PhonemeWordSource` table.
 * @tparam N Number of table entries (deduced)
 * @tparam WordBytes Total word-character count (pass
 *         `tts_compact_dict_detail::cxTotalWordBytes(table)`)
 * @tparam PhonemeCount Total phoneme count (pass
 *         `tts_compact_dict_detail::cxTotalPhonemeCount(table)`)
 * @details Building this object is a compile-time constant expression --
 * the packed arrays end up in read-only memory exactly as if they'd been
 * generated by an offline script, but the source stays a plain table of
 * `PH_WORD(...)` rows with no separate build step. An out-of-alphabetical-
 * order word fails the *build* (binary search requires sorted entries)
 * rather than corrupting the dictionary silently at runtime; an
 * unrecognized phoneme name is simply not a valid `Phone` enumerator, so
 * it's already a compiler error at the PH_WORD() call site.
 * Use TTS_COMPACT_DICTIONARY() below instead of naming this type directly.
 */
template <size_t N, size_t WordBytes, size_t PhonemeCount>
struct CompactPhonemeDictionaryData {
  std::array<uint32_t, N + 1> wordOffsets{};
  std::array<char, WordBytes> wordsBlob{};
  std::array<uint32_t, N + 1> phonemeOffsets{};
  std::array<uint8_t, PhonemeCount> phonemeData{};

  constexpr CompactPhonemeDictionaryData(const PhonemeWordSource (&table)[N]) {
    using namespace tts_compact_dict_detail;
    size_t wPos = 0, pPos = 0;
    wordOffsets[0] = 0;
    phonemeOffsets[0] = 0;
    for (size_t i = 0; i < N; ++i) {
      if (i > 0 && !cxWordLess(table[i - 1].word, table[i].word)) {
        throw "CompactPhonemeDictionaryData: source table is not sorted "
              "(words must be strictly ascending for binary search)";
      }
      size_t wlen = cxStrLen(table[i].word);
      for (size_t j = 0; j < wlen; ++j) wordsBlob[wPos + j] = table[i].word[j];
      wPos += wlen;
      wordOffsets[i + 1] = static_cast<uint32_t>(wPos);

      for (size_t j = 0; j < table[i].phonemeCount; ++j) {
        phonemeData[pPos++] = table[i].phonemeData[j];
      }
      phonemeOffsets[i + 1] = static_cast<uint32_t>(pPos);
    }
  }
};

/// Declares `name##Data` (the compile-time-packed storage) and `name`
/// (a ready-to-use CompactPhonemeDictionary bound to it) from a
/// `static constexpr PhonemeWordSource table[] = { PH_WORD(...), ... };`.
#define TTS_COMPACT_DICTIONARY(name, table)                                        \
  constexpr CompactPhonemeDictionaryData<                                          \
      sizeof(table) / sizeof((table)[0]),                                          \
      tts_compact_dict_detail::cxTotalWordBytes(table),                            \
      tts_compact_dict_detail::cxTotalPhonemeCount(table)>                         \
      name##Data(table);                                                           \
  const CompactPhonemeDictionary name(                                             \
      name##Data.wordOffsets.data(), name##Data.wordsBlob.data(),                  \
      name##Data.phonemeOffsets.data(), name##Data.phonemeData.data(),             \
      sizeof(table) / sizeof((table)[0]))
