#!/usr/bin/env python3
"""
Generate a C++ header file with SoundEntry array from WAV files.
This script reads all WAV files from a specified directory (default: pcm8bit)
and generates a header file containing the binary data as C++ arrays.
"""

import os
import sys
import shutil
import struct
import argparse
from pathlib import Path

def read_wav_data(file_path):
    """Read WAV file and extract the audio data portion (skip header)"""
    with open(file_path, 'rb') as f:
        # Read WAV header to find data chunk
        # Standard WAV format: RIFF header (12 bytes) + fmt chunk + data chunk
        f.read(4)  # "RIFF"
        file_size = struct.unpack('<I', f.read(4))[0]
        f.read(4)  # "WAVE"
        
        # Find data chunk
        while True:
            chunk_id = f.read(4)
            if len(chunk_id) < 4:
                break
            chunk_size = struct.unpack('<I', f.read(4))[0]
            
            if chunk_id == b'data':
                # Found data chunk, read the audio data
                return f.read(chunk_size)
            else:
                # Skip this chunk
                f.read(chunk_size)
                # Handle odd-sized chunks (WAV format requires even alignment)
                if chunk_size % 2 == 1:
                    f.read(1)
        
        return b''  # No data chunk found

# A WAV file's stem is normally both the filesystem-safe identifier
# (individual header filename, C++ array name) AND the runtime lookup key
# embedded in ArpabetWAVDictionary's SoundEntry (what
# AudioDictionary::getSoundEntry() matches against). Those need to diverge
# for a modifier-tagged phoneme like "AF:" (German long a, see
# PhonemeModifiers.h) -- a literal colon in a filename/#include path is
# legal on Linux but not portably safe across the toolchains this library
# targets (Arduino IDE, Windows-hosted ESP-IDF, ...), so such a phoneme's
# WAV file uses "-" in place of the tag's ":" (e.g. "AF-.wav") and is
# mapped here back to its real tagged lookup key -- the file/array naming
# stays ASCII-safe, only the string SoundEntry is constructed with ":".
DISPLAY_NAME_OVERRIDES = {
    "AF-": "AF:",
}

def generate_cpp_headers(input_dir, output_dir, format_name, force_overwrite=False):
    """Generate separate C++ header files for each WAV file and a main dictionary header"""
    
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    
    if not input_path.exists():
        print(f"Error: Directory {input_dir} does not exist!")
        return False
    
    # Create output directory if it doesn't exist
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Get all WAV files
    wav_files = sorted(input_path.glob("*.wav"))
    
    if not wav_files:
        print(f"No WAV files found in {input_dir}")
        return False
    
    print(f"Found {len(wav_files)} WAV files to process...")
    print(f"Processing {format_name.upper()} format from: {input_dir}")
    print()
    
    # Generate individual header files for each WAV file
    sound_entries = []
    
    for wav_file in wav_files:
        # Get filename without extension (filesystem-safe identifier) and
        # its runtime lookup key (may differ -- see DISPLAY_NAME_OVERRIDES).
        name = wav_file.stem
        display_name = DISPLAY_NAME_OVERRIDES.get(name, name)

        # Read WAV data
        try:
            wav_data = read_wav_data(wav_file)
            if not wav_data:
                print(f"Warning: No data found in {wav_file}")
                continue

            # Generate C++ array name (replace special chars with underscores)
            array_name = f"phoneme_data_{name.replace('-', '_').replace(' ', '_')}"
            
            # Generate individual header file content
            individual_header_content = []
            individual_header_content.append('#pragma once')
            individual_header_content.append('#include <cstdint>')
            individual_header_content.append('')
            individual_header_content.append(f'// Auto-generated phoneme data for {name} ({format_name.upper()} format)')
            individual_header_content.append('// Generated by generate_wav_dictionary.py')
            individual_header_content.append('')
            individual_header_content.append(f'// Data for ARPAbet phoneme {name}')
            individual_header_content.append(f'const uint8_t {array_name}[] = {{')
            
            # Convert bytes to hex values, 16 per line
            hex_values = []
            for i, byte in enumerate(wav_data):
                hex_values.append(f'0x{byte:02X}')
                if (i + 1) % 16 == 0:
                    individual_header_content.append(f'    {", ".join(hex_values)},')
                    hex_values = []
            
            # Add remaining bytes
            if hex_values:
                individual_header_content.append(f'    {", ".join(hex_values)}')
            
            individual_header_content.append('};')
            individual_header_content.append('')
            individual_header_content.append(f'// Size of the data array')
            individual_header_content.append(f'const size_t {array_name}_size = {len(wav_data)};')
            
            # Write individual header file
            individual_header_file = output_path / f"{name}.h"
            with open(individual_header_file, 'w') as f:
                f.write('\n'.join(individual_header_content))
            
            # Store entry info. 'name' stays filesystem-safe (used for the
            # data/audio/arpabet/ copy AudioDictionarySD reads directly by
            # phoneme-name path -- colon is illegal in FAT32 filenames, the
            # typical SD card filesystem, so a tagged phoneme like "AF:"
            # can't round-trip through that class's simple path convention
            # regardless of what we name things here; 'display_name' is
            # the real runtime lookup key, used only for the in-memory
            # ArpabetWAVDictionary SoundEntry string (a C string literal,
            # no filesystem involved).
            sound_entries.append({
                'name': name,
                'display_name': display_name,
                'array_name': array_name,
                'size': len(wav_data),
                'header_file': f"{name}.h",
                'source_wav': wav_file,
            })

            print(f"Generated {individual_header_file}: {len(wav_data)} bytes")
            
        except Exception as e:
            print(f"Error processing {wav_file}: {e}")
            continue
    
    # Also copy each source WAV verbatim into data/audio/arpabet/ -- the
    # runtime-loadable counterpart to the PROGMEM headers above (see
    # data/README.md), used by AudioDictionarySD instead of
    # ArpabetWAVDictionary. Kept in sync here so it never drifts from the
    # PROGMEM data: both are generated from the exact same source files in
    # the same run, not maintained separately.
    data_dir = find_project_root() / 'data' / 'audio' / 'arpabet'
    data_dir.mkdir(parents=True, exist_ok=True)
    for entry in sound_entries:
        shutil.copy2(entry['source_wav'], data_dir / f"{entry['name']}.wav")
    print(f"Copied {len(sound_entries)} WAV files to {data_dir}")

    # Umbrella header: Data/wav/arpabet.h including each individual
    # Data/wav/arpabet/{NAME}.h -- lets the main dictionary header include
    # just one line instead of 41, matching the convention already used
    # for diphones (Data/wav/diphones.h).
    umbrella_lines = ['#pragma once', '']
    for entry in sound_entries:
        umbrella_lines.append(f'#include "arpabet/{entry["header_file"]}"')
    umbrella_file = output_path.parent / "arpabet.h"
    with open(umbrella_file, 'w') as f:
        f.write('\n'.join(umbrella_lines) + '\n')
    print(f"Wrote umbrella header: {umbrella_file}")

    # Generate the main dictionary header file
    main_header_content = []
    main_header_content.append('#pragma once')
    main_header_content.append('#include <cstddef>')
    main_header_content.append('#include <cstdint>')
    main_header_content.append('#include <vector>')
    main_header_content.append('#include <cstring>')
    main_header_content.append('#include "AudioDictionary.h"')
    main_header_content.append('#include "SoundEntry.h"')
    main_header_content.append('#include "../Data/wav/arpabet.h"')
    main_header_content.append('')
    main_header_content.append(f'// Auto-generated phoneme dictionary from {format_name.upper()} WAV files')
    main_header_content.append('// Generated by generate_wav_dictionary.py')
    main_header_content.append('')
    
    # Generate the SoundEntry array with 8-bit format specified
    main_header_content.append('// Array of all ARPAbet phonemes')
    main_header_content.append(f'const SoundEntry ARPABET_PHONEMES[{len(sound_entries)}] = {{')
    
    for i, entry in enumerate(sound_entries):
        comma = ',' if i < len(sound_entries) - 1 else ''
        # Include 8-bit format in SoundEntry constructor
        main_header_content.append(f'    SoundEntry("{entry["display_name"]}", {entry["size"]}, {entry["array_name"]}, 8){comma}')
    
    main_header_content.append('};')
    main_header_content.append('')
    main_header_content.append(f'// Total number of ARPAbet phonemes')
    main_header_content.append(f'const size_t NUM_ARPABET_PHONEMES = {len(sound_entries)};')
    main_header_content.append('')
    
    main_header_content.append('/**')
    main_header_content.append(' * @brief Static global AudioDictionary instance with ARPAbet WAV phonemes')
    main_header_content.append(' * @details This global variable provides immediate access to the ARPAbet phoneme dictionary')
    main_header_content.append(' *          without needing to instantiate a class. It\'s automatically initialized with')
    main_header_content.append(f' *          all {len(sound_entries)} ARPAbet phonemes at 8kHz sample rate with 8-bit source data.')
    main_header_content.append(' */')
    main_header_content.append('static AudioDictionary ArpabetWAVDictionary(ARPABET_PHONEMES, NUM_ARPABET_PHONEMES, 8000, PhonemeType::ARPAbet, 1, 16);')
    
    
    # Write main dictionary header file
    # Data/wav/arpabet -> Data/wav -> Data -> TinyTTSTools -> SoundDictionary/ArpabetWAVDictionary.h
    # (a sibling of Data/, not output_path.parent.parent -- that stale
    # assumption predates the Data/ subfolder reorg and pointed at
    # src/TinyTTSTools/ArpabetWAVDictionary.h, which nothing includes).
    main_header_file = output_path.parent.parent.parent / "SoundDictionary" / "ArpabetWAVDictionary.h"
    
    # Check if main header file already exists
    if main_header_file.exists() and not force_overwrite:
        print(f"\n✓ {main_header_file} already exists - skipping creation")
        print("  Only individual phoneme headers were updated")
        print("  To regenerate the main header, use --force flag or delete it first")
        return True
    
    # File doesn't exist or force overwrite is enabled, create it with data only
    file_existed = main_header_file.exists()
    try:
        with open(main_header_file, 'w') as f:
            f.write('\n'.join(main_header_content))
        
        if force_overwrite and file_existed:
            print(f"\n✓ Force-overwrote {main_header_file}")
            print("  Updated ArpabetWAVDictionary.h with static global variable")
        else:
            print(f"\n✓ Created new {main_header_file}")
        print("  Generated complete ArpabetWAVDictionary.h with static global variable")
        print("  Ready to use directly in TinyTTSTools projects")
        print(f"Total ARPAbet phonemes: {len(sound_entries)}")
        
        # Calculate total size
        total_size = sum(entry['size'] for entry in sound_entries)
        print(f"Total data size: {total_size} bytes ({total_size/1024:.1f} KB)")
        print(f"Format: {format_name.upper()}")
        
        # Provide updated usage advice
        print()
        print("Usage with TinyTTSTools:")
        print("  #include \"TinyTTSTools/ArpabetWAVDictionary.h\"")
        print("  PhonemeVocoder synth(ArpabetWAVDictionary);  // Use global variable directly")
        
        return True
        
    except Exception as e:
        print(f"Error writing to {main_header_file}: {e}")
        return False

def find_project_root():
    """Find the TinyTTSTools project root directory"""
    current_dir = Path(__file__).parent.absolute()
    
    # Look for markers that indicate the project root
    # library.properties is the most reliable indicator for Arduino libraries
    primary_markers = ['library.properties']
    secondary_markers = ['CMakeLists.txt', 'README.md']
    
    # Start from current directory and go up
    search_dir = current_dir
    for _ in range(10):  # Increase search depth
        # First check for primary markers (most reliable)
        for marker in primary_markers:
            if (search_dir / marker).exists():
                return search_dir
        
        # Then check for secondary markers with additional validation
        for marker in secondary_markers:
            if (search_dir / marker).exists():
                # Additional validation - check if src/TinyTTSTools exists
                if (search_dir / 'src' / 'TinyTTSTools').exists():
                    # Make sure this isn't a nested src directory
                    if not str(search_dir).endswith('/setup'):
                        return search_dir
        
        search_dir = search_dir.parent
        
        # Stop if we reach filesystem root
        if search_dir == search_dir.parent:
            break
    
    # Fallback: assume we're in setup/audio/phonemes-from-espeak and go up 3 levels
    fallback_root = current_dir.parent.parent.parent
    print(f"Warning: Using fallback project root detection: {fallback_root}")
    return fallback_root

def get_format_info(input_dir):
    """Determine format name from directory name"""
    dir_name = Path(input_dir).name.lower()
    
    format_mapping = {
        'adpcm': 'ADPCM',
        'pcm8bit': 'PCM8',
        'pcm8': 'PCM8', 
        'ulaw': 'µ-law',
        'alaw': 'A-law',
        'original': 'Original'
    }
    
    return format_mapping.get(dir_name, dir_name.upper())

def main():
    parser = argparse.ArgumentParser(description='Generate C++ header files from ARPAbet phoneme WAV files')
    
    parser.add_argument('--input', '-i',
                       default='pcm8bit',
                       help='Input directory containing WAV files (default: pcm8bit)')
    
    parser.add_argument('--output', '-o',
                       default=None,
                       help='Output directory for generated headers (default: auto-detect project root)')
    
    parser.add_argument('--list-formats', '-l',
                       action='store_true',
                       help='List available input directories and exit')
    
    parser.add_argument('--force', '-f',
                       action='store_true',
                       help='Force overwrite of existing ArpabetWAVDictionary.h file')
    
    args = parser.parse_args()
    
    # Determine output directory
    if args.output is None:
        # Auto-detect project root and set default output path
        project_root = find_project_root()
        default_output = project_root / 'src' / 'TinyTTSTools' / 'Data' / 'wav' / 'arpabet'
        args.output = str(default_output)
    
    # List available formats if requested
    if args.list_formats:
        print("Available input directories:")
        print("=" * 40)
        
        current_dir = Path('.')
        format_dirs = []
        
        # Look for common format directories
        common_formats = ['original', 'adpcm', 'pcm8bit', 'pcm8', 'ulaw', 'alaw']
        for fmt_dir in common_formats:
            if (current_dir / fmt_dir).exists():
                wav_count = len(list((current_dir / fmt_dir).glob("*.wav")))
                if wav_count > 0:
                    format_info = get_format_info(fmt_dir)
                    format_dirs.append((fmt_dir, format_info, wav_count))
        
        if format_dirs:
            for dir_name, format_name, count in format_dirs:
                marker = " (default)" if dir_name == 'pcm8bit' else ""
                print(f"  {dir_name:12} - {format_name} format ({count} files){marker}")
        else:
            print("  No format directories with WAV files found")
            print("  Generate phoneme audio first:")
            print("    ./generate_arpabet_phonemes_mbrola.sh")
        return
    
    # Determine format name from input directory
    format_name = get_format_info(args.input)
    
    print(f"ARPAbet {format_name} WAV to C++ Header Generator")
    print("=" * 60)
    print(f"Input directory: {args.input}")
    print(f"Output directory: {args.output}")
    print(f"Format: {format_name}")
    print()
    
    # Generate the header files
    success = generate_cpp_headers(args.input, args.output, format_name, args.force)
    
    if success:
        print()
        print("🎉 Header generation completed successfully!")
        print()
        print("Next steps:")
        print("1. Include \"TinyTTSTools/ArpabetWAVDictionary.h\" in your project")
        print("2. Use ArpabetWAVDictionary as a static global variable")
        print("3. Example: PhonemeVocoder synth(ArpabetWAVDictionary);")
        print("4. Test audio playback with TinyTTSTools")
    else:
        print("❌ Header generation failed")
        sys.exit(1)

if __name__ == "__main__":
    main()
